name: .NET

on:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -- configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger trx --results-directory "TestResults" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - name: Publish Test
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Test Results on dev
        path: ./TestResults/*.trx
        reporter: dotnet-trx
    - name: Create an Issue
      if: failure()
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/ultimate_issue_template.md      
    - uses: codecov/codecov-action@v2
      with:
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true
        
    - name: Pull request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}


        
   
